#pragma once

#if CONFIG_IDF_TARGET_ESP32

#define ESP_PIN_FREQ_TANK 36
#define ESP_PIN_FREQ_SOIL 39
#define ESP_PIN_V_MEAS 34
#define ESP_PIN_CURR_MEAS 35
#define ESP_PIN_TANK_MIN_SENS 32
#define ESP_PIN_TANK_MAX_SENS 33
#define ESP_PIN_HW_REV 12
#define ESP_PIN_DEHUM_FAN_SENSE 26
#define ESP_PIN_LIGHT 25
#define ESP_PIN_DHT21_DATA 27
#define ESP_PIN_DS18B20_DATA 17
#define ESP_PIN_WATER_PUMP 23
#define ESP_PIN_BMP280_SCL 22
#define ESP_PIN_FLOOD_SENS 22
#define ESP_PIN_U0_TX 1
#define ESP_PIN_U0_RX 3
#define ESP_PIN_BMP280_SDA 21
#define ESP_PIN_COOL_FAN 19
#define ESP_PIN_DEHUM_FAN 18
#define ESP_PIN_COOL_PUMP 5
#define ESP_PIN_LIGHT_SENSOR 14
#define ESP_PIN_BURN 16
#define ESP_PIN_PELT 4
#define ESP_PIN_IO0 0

#elif CONFIG_IDF_TARGET_ESP32S3

#define ESP_PIN_FREQ_TANK 4
#define ESP_PIN_FREQ_SOIL 5
#define ESP_PIN_V_MEAS 6
#define ESP_PIN_CURR_MEAS 7
#define ESP_PIN_TANK_MIN_SENS 15
#define ESP_PIN_TANK_MAX_SENS 16
#define ESP_PIN_HW_REV 17
#define ESP_PIN_DEHUM_FAN_SENSE 18
#define ESP_PIN_LIGHT 8
#define ESP_PIN_DHT21_DATA 19
#define ESP_PIN_DS18B20_DATA 20
#define ESP_PIN_WATER_PUMP 1
#define ESP_PIN_BMP280_SCL 2
#define ESP_PIN_FLOOD_SENS 2
#define ESP_PIN_U0_TX 43
#define ESP_PIN_U0_RX 44
#define ESP_PIN_BMP280_SDA 42
#define ESP_PIN_COOL_FAN 40
#define ESP_PIN_DEHUM_FAN 39
#define ESP_PIN_COOL_PUMP 38
#define ESP_PIN_LIGHT_SENSOR 37
#define ESP_PIN_BURN 36
#define ESP_PIN_PELT 35
#define ESP_PIN_IO0 0

#endif
